version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"   # You can set to daily if needed
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    commit-message:
      prefix: "deps"
      include: "scope"
