name: Code Review & Security Check

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  lint-and-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies if Node project exists
        run: |
          if [ -f "package.json" ]; then
            npm install
          else
            echo "No package.json found — skipping dependency install."
          fi

      - name: Run ESLint if config exists
        run: |
          if [ -f ".eslintrc.json" ]; then
            npx eslint . --ext .js || exit 1
          else
            echo "No ESLint config found — skipping lint."
          fi

      - name: Check for vulnerabilities (log only, don't fail)
        run: |
          if [ -f "package.json" ]; then
            npm audit --audit-level=moderate || echo "Vulnerabilities found — continue for review."
          else
            echo "No Node project — skipping npm audit."
          fi

  codeql-analysis:
    name: 🔍 CodeQL Security Scan
    needs: lint-and-audit
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Scan
        uses: github/codeql-action/analyze@v3
