name: Auto Release Notes

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g., v1.0.0)"
        required: true
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  generate-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Release Notes
        id: notes
        uses: actions/github-script@v7
        with:
          script: |
            const tag = context.payload.inputs?.tag || context.ref.replace("refs/tags/", "");
            const { data: notes } = await github.rest.repos.generateReleaseNotes({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag
            });
            core.setOutput("body", notes.body);

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref }}
          body: ${{ steps.notes.outputs.body }}
